name: Update test262 Expectations and Metrics

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'

env:
  CARGO_TERM_COLOR: always

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.head_ref || 'main' }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
        timeout-minutes: 20
      - name: Checkout test262 submodule
        run: git submodule update --init
      - name: Test262
        run: cargo run --bin test262 -- --noprogress --update
        timeout-minutes: 15
      - name: Update expectations and metrics
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tests/expectations.json
          git add tests/metrics.json
          git commit -m "Update test262 expectations and metrics"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
